Tensorflow basics:

- Video Link: https://www.youtube.com/watch?v=tpCFfeUEGs8
- Docs Link: https://www.tensorflow.org/api_docs/python
- Code/Materials Link: https://github.com/mrdbourke/tensorflow-deep-learning/blob/main/00_tensorflow_fundamentals.ipynb

In [30]:
import tensorflow as tf  # Importing tensorflow

print(tf.__version__)


2.10.0


### Create tensors with tf.constant():

- You can't change constant - i guess


In [31]:
# Create tensors with tf.constant()
scaler = tf.constant(7)
scaler


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [32]:
# Check the number of dimensions of the tensors (ndim stands for the number of dimensions)
scaler.ndim

# Excepted 0 because scaler shape=() has no element


0

In [33]:
# Create a vector
vector = tf.constant([10, 10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [34]:
# Check the dimensions of the vector
vector.ndim

# Excepted 1 because vector shape=(1,) it has one element '1'


1

In [35]:
# Create a matrix (has more than one dimension)
matrix = tf.constant([[3, 7],
                      [5, 7]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 7],
       [5, 7]])>

In [36]:
matrix.ndim
# Excepted 2 because matrix shape=(2, 2) it has two element '2, 2'


2

In [37]:
another_matrix = tf.constant([[10., 45.],
                              [3., 5.],
                              [7., 9.],
                              ], dtype=tf.float16)  # Specify the data type with the dtype parameter
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 45.],
       [ 3.,  5.],
       [ 7.,  9.]], dtype=float16)>

In [38]:
# Excepted 2 because another_matrix shape=(3, 2) it has two element '3, 2'
another_matrix.ndim


2

In [39]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3, 5],
                       [4, 5, 6, 6]],
                      [[7, 8, 9, 7],
                      [10, 11, 12, 7]],
                      [[13, 14, 15, 8], [16, 17, 18, 4]]])

tensor
# Here in shape=(3, 2, 4), '3' means there is three list and 2 means that list contains 2 list and 4 means that list contains 4 elements


<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  5],
        [ 4,  5,  6,  6]],

       [[ 7,  8,  9,  7],
        [10, 11, 12,  7]],

       [[13, 14, 15,  8],
        [16, 17, 18,  4]]])>

In [40]:
tensor.ndim
# Excepted 2 because another_matrix shape=(3, 2, 4) it has two element '3, 2, 4'


3

### Create tensors with tf.Variable():

- You can change variables


In [41]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [42]:
# Let's try to change element of tensors
# changeable_tensor[0] = 20 # NOTE: It will not work
changeable_tensor[0].assign(20)  # This will work
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20,  7])>

### Creating Random Tensors:


In [43]:
# Creating two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 4))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 4))

# Are they equal?
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535806 , -0.5716629 ,  0.1480774 , -0.23362991]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535806 , -0.5716629 ,  0.1480774 , -0.23362991]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

### Shuffle The Elements:

- It is valuable when you want to shuffle your data so the inherent order doesn't effect learning


In [44]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 8]])

# Shuffle or non-shuffled  tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  8],
       [10,  7]])>

In [45]:
# Shuffle or non-shuffled  tensor

tf.random.set_seed(42)  # Global level random seed
tf.random.shuffle(not_shuffled, seed=42)  # operation level random seed


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  8]])>

### Other way to make tensors

In [46]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [47]:
# Create a tensor of all zeros
tf.zeros([4, 10])

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

Teh main difference between NumPy arrays and tensorFlow is that tensors can be run on GPU(much faster for numerical computing)

In [48]:
# You can also turn Numpy arrays into tensors
import numpy as np
numpy_A  = np.arange(1, 25, dtype=np.int32) # Create a numpy array between 1 and 25
numpy_A 
# X = tf.constant(some_matrix) # Capital for matrix or tensors
# y = tf.constant(vector) # Non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [49]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [50]:
#  Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3,2,4))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 2, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [51]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [52]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 2, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=48>)

In [53]:
2*3*2*4

48

In [54]:
# Get various attributes of our tensors
print("Datatype of every element:", rank_4_tensor.dtype)
print("Shape of tensor:", rank_4_tensor.shape)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Total number of element in our tensor:", tf.size(rank_4_tensor))
print("Total number of element in our tensor:", tf.size(rank_4_tensor).numpy())
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])

Datatype of every element: <dtype: 'float32'>
Shape of tensor: (2, 3, 2, 4)
Number of dimensions (rank): 4
Total number of element in our tensor: tf.Tensor(48, shape=(), dtype=int32)
Total number of element in our tensor: 48
Elements along the 0 axis: 2
Elements along the last axis: 4


### Indexing Tensors
Tensors can be indexed just like python lists.

In [55]:
some_list = [1,2,3,4,]
some_list[:2] #Get First 2 elements

[1, 2]

In [59]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
some_list[:1]


In [64]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 2, 1), dtype=float32, numpy=
array([[[[0.],
         [0.]]]], dtype=float32)>